#!/usr/bin/env bash

script="$1"

cd "$(dirname "${BASH_SOURCE[0]}")"

./setup.py "$script"
ip=$(./config.py)

function jsonString {
  egrep -o -m1 '"'"$1"'" *: *"[^"]*"' | egrep -o -m1 '"[^"]*"$' | egrep -o -m1 '[^"]*'
}
