#!/usr/bin/env bash

cd "$(dirname "${BASH_SOURCE[0]}")"

ip=$(cat .ip | egrep -o "([0-9]{1,3}\.){3}[0-9]{1,3}")

if [[ -z "$ip" ]]; then
  ./selectIp
  ip=$(cat .ip | egrep -o "([0-9]{1,3}\.){3}[0-9]{1,3}")
fi

function jsonString {
  egrep -o -m1 '"'"$1"'" *: *"[^"]*"' | egrep -o -m1 '"[^"]*"$' | egrep -o -m1 '[^"]*'
}
